[package]
name = "acars_router"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
log = "0.4.19"
tokio = { version = "1.29.1", features = ["full", "tracing"] }
chrono = "0.4.26"
serde = { version = "1.0.182", features = ["derive"] }
serde_json = "1.0.104"
failure = "0.1.8"
acars_config = { path = "../../libraries/acars_config" }
sdre-rust-logging = { git = "https://github.com/sdr-enthusiasts/sdre-rust-logging.git" }
acars_connection_manager = { path = "../../libraries/acars_connection_manager" }
